import type { BlockManifest } from "../manifest";

export const companiesBlock: BlockManifest = {
  kind: "block",
  name: "companies",
  displayName: "Empresas",
  description:
    "B2B companies the organization interacts with — clients, prospects, partners. Distinct from PartnerBrand (affiliate program brands) and NetworkProfile (program participants). Each company has identity (name, legalName, taxId, website, domain, logoUrl), segmentation (industry, size enum SMALL/MEDIUM/LARGE/ENTERPRISE), corporate contact (email, phone, social), inline address, and a one-to-many relationship with Contacts. Deleting a company sets contacts.companyId to null (no cascade).",
  types: ["company"],
  capabilities: ["read", "create", "update", "delete"],
  models: ["Company"],
  dependencies: [],
  paths: {
    components: "src/components/companies/",
    pages: "src/app/admin/blocks/companies/",
    api: "src/app/api/companies/",
    validators: "src/lib/validators/companies.ts",
    provider: "src/lib/chat/providers/company.provider.ts",
  },
  actions: [
    {
      name: "list_companies",
      description:
        "List companies with optional filters by industry, size, ownerId, tag, and keyword search across name/legalName/domain/website/industry/email/contentText",
      method: "GET",
      endpoint: "/api/companies",
      parametersSchema: {
        type: "object",
        properties: {
          industry: { type: "string" },
          size: {
            type: "string",
            enum: ["SMALL", "MEDIUM", "LARGE", "ENTERPRISE"],
          },
          ownerId: { type: "string" },
          tag: { type: "string" },
          search: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
        },
      },
      responseDescription:
        "{ companies: Company[], total: number } — each company includes _count.contacts",
    },
    {
      name: "get_company",
      description:
        "Get a single company by ID, including up to 50 linked contacts and total contact count",
      method: "GET",
      endpoint: "/api/companies/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Company with `contacts` array and `_count.contacts`",
    },
    {
      name: "create_company",
      description: "Create a new company",
      method: "POST",
      endpoint: "/api/companies",
      parametersSchema: {
        type: "object",
        properties: {
          name: { type: "string" },
          legalName: { type: "string" },
          taxId: { type: "string" },
          website: { type: "string" },
          domain: { type: "string" },
          logoUrl: { type: "string" },
          industry: { type: "string" },
          size: {
            type: "string",
            enum: ["SMALL", "MEDIUM", "LARGE", "ENTERPRISE"],
          },
          email: { type: "string" },
          phone: { type: "string" },
          linkedinUrl: { type: "string" },
          twitterHandle: { type: "string" },
          street: { type: "string" },
          street2: { type: "string" },
          city: { type: "string" },
          state: { type: "string" },
          zip: { type: "string" },
          country: { type: "string" },
          description: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          ownerId: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["name"],
      },
      requiredFields: ["name"],
      responseDescription: "Created company record",
    },
    {
      name: "update_company",
      description: "Update an existing company",
      method: "PATCH",
      endpoint: "/api/companies/{id}",
      parametersSchema: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          legalName: { type: "string" },
          taxId: { type: "string" },
          website: { type: "string" },
          domain: { type: "string" },
          logoUrl: { type: "string" },
          industry: { type: "string" },
          size: {
            type: "string",
            enum: ["SMALL", "MEDIUM", "LARGE", "ENTERPRISE"],
          },
          email: { type: "string" },
          phone: { type: "string" },
          linkedinUrl: { type: "string" },
          twitterHandle: { type: "string" },
          street: { type: "string" },
          street2: { type: "string" },
          city: { type: "string" },
          state: { type: "string" },
          zip: { type: "string" },
          country: { type: "string" },
          description: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          ownerId: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Updated company record",
    },
    {
      name: "delete_company",
      description:
        "Delete a company. Linked contacts have their companyId set to null (onDelete: SetNull); no cascade.",
      method: "DELETE",
      endpoint: "/api/companies/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "{ deleted: true }",
    },
  ],
};
