import type { BlockManifest } from "../manifest";

export const contactsBlock: BlockManifest = {
  kind: "block",
  name: "contacts",
  displayName: "Contatos",
  description:
    "CRM contacts — leads, prospects, customers, and other people the company interacts with. Distinct from NetworkProfile (which is dedicated to the partner program). Each contact has identity (firstName, lastName, email, phone), professional info (jobTitle, department), polymorphic links (companyId → companies block, ownerId → user/profile), origin source, address, and social fields (birthday, linkedinUrl, twitterHandle). Contacts use tags for lifecycle classification (lead/prospect/customer) instead of a status enum — formal pipeline lives in the deals block.",
  types: ["contact"],
  capabilities: ["read", "create", "update", "delete"],
  models: ["Contact"],
  dependencies: [],
  paths: {
    components: "src/components/contacts/",
    pages: "src/app/admin/blocks/contacts/",
    api: "src/app/api/contacts/",
    validators: "src/lib/validators/contacts.ts",
    provider: "src/lib/chat/providers/contact.provider.ts",
  },
  actions: [
    {
      name: "list_contacts",
      description:
        "List contacts with optional filters by companyId, ownerId, source, tag, and keyword search across name/email/phone/jobTitle/department/content",
      method: "GET",
      endpoint: "/api/contacts",
      parametersSchema: {
        type: "object",
        properties: {
          companyId: { type: "string" },
          ownerId: { type: "string" },
          source: { type: "string" },
          tag: { type: "string" },
          search: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
        },
      },
      responseDescription: "{ contacts: Contact[], total: number }",
    },
    {
      name: "get_contact",
      description: "Get a single contact by ID",
      method: "GET",
      endpoint: "/api/contacts/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Single contact record",
    },
    {
      name: "create_contact",
      description: "Create a new contact",
      method: "POST",
      endpoint: "/api/contacts",
      parametersSchema: {
        type: "object",
        properties: {
          firstName: { type: "string" },
          lastName: { type: "string" },
          email: { type: "string" },
          phone: { type: "string" },
          avatarUrl: { type: "string" },
          jobTitle: { type: "string" },
          department: { type: "string" },
          companyId: { type: "string" },
          ownerId: { type: "string" },
          source: { type: "string" },
          street: { type: "string" },
          street2: { type: "string" },
          city: { type: "string" },
          state: { type: "string" },
          zip: { type: "string" },
          country: { type: "string" },
          birthday: { type: "string", description: "ISO date string" },
          linkedinUrl: { type: "string" },
          twitterHandle: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["firstName"],
      },
      requiredFields: ["firstName"],
      responseDescription: "Created contact record",
    },
    {
      name: "update_contact",
      description: "Update an existing contact",
      method: "PATCH",
      endpoint: "/api/contacts/{id}",
      parametersSchema: {
        type: "object",
        properties: {
          id: { type: "string" },
          firstName: { type: "string" },
          lastName: { type: "string" },
          email: { type: "string" },
          phone: { type: "string" },
          avatarUrl: { type: "string" },
          jobTitle: { type: "string" },
          department: { type: "string" },
          companyId: { type: "string" },
          ownerId: { type: "string" },
          source: { type: "string" },
          street: { type: "string" },
          street2: { type: "string" },
          city: { type: "string" },
          state: { type: "string" },
          zip: { type: "string" },
          country: { type: "string" },
          birthday: { type: "string" },
          linkedinUrl: { type: "string" },
          twitterHandle: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Updated contact record",
    },
    {
      name: "delete_contact",
      description: "Delete a contact permanently",
      method: "DELETE",
      endpoint: "/api/contacts/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "{ deleted: true }",
    },
  ],
};
