import type { BlockManifest } from "../manifest";

const STAGE_ENUM = [
  "LEAD",
  "QUALIFIED",
  "PROPOSAL",
  "NEGOTIATION",
  "WON",
  "LOST",
];

export const dealsBlock: BlockManifest = {
  name: "deals",
  displayName: "Oportunidades",
  description:
    "Sales pipeline opportunities (deals). Each deal has a title, stage (LEAD/QUALIFIED/PROPOSAL/NEGOTIATION/WON/LOST), amount with currency, probability (0-100), expected close date, optional links to a Contact and/or Company, owner, source, tags, and rich content. Deleting a linked Contact or Company sets the link to null (no cascade). Closing to WON/LOST auto-stamps closedAt unless provided explicitly.",
  domain: "sales",
  types: ["deal"],
  capabilities: ["read", "create", "update", "delete"],
  models: ["Deal"],
  dependencies: [],
  paths: {
    components: "src/components/deals/",
    pages: "src/app/admin/blocks/deals/",
    api: "src/app/api/deals/",
    validators: "src/lib/validators/deals.ts",
    provider: "src/lib/chat/providers/deal.provider.ts",
  },
  actions: [
    {
      name: "list_deals",
      description:
        "List deals with optional filters by stage, contactId, companyId, ownerId, tag, and keyword search across title/description/contentText/source/contact name/company name",
      method: "GET",
      endpoint: "/api/deals",
      parametersSchema: {
        type: "object",
        properties: {
          stage: { type: "string", enum: STAGE_ENUM },
          contactId: { type: "string" },
          companyId: { type: "string" },
          ownerId: { type: "string" },
          tag: { type: "string" },
          search: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
        },
      },
      responseDescription:
        "{ deals: Deal[], total: number } — each deal includes contact { id, firstName, lastName } and company { id, name }",
    },
    {
      name: "get_deal",
      description: "Get a single deal by ID with linked contact and company",
      method: "GET",
      endpoint: "/api/deals/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Deal with `contact` and `company` includes",
    },
    {
      name: "create_deal",
      description: "Create a new sales opportunity",
      method: "POST",
      endpoint: "/api/deals",
      parametersSchema: {
        type: "object",
        properties: {
          title: { type: "string" },
          description: { type: "string" },
          stage: { type: "string", enum: STAGE_ENUM },
          amount: { type: "number" },
          currency: { type: "string" },
          probability: { type: "number" },
          expectedCloseDate: { type: "string" },
          closedAt: { type: "string" },
          lostReason: { type: "string" },
          contactId: { type: "string" },
          companyId: { type: "string" },
          ownerId: { type: "string" },
          source: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["title"],
      },
      requiredFields: ["title"],
      responseDescription: "Created deal record",
    },
    {
      name: "update_deal",
      description:
        "Update a deal. Setting stage to WON/LOST auto-stamps closedAt if not provided.",
      method: "PATCH",
      endpoint: "/api/deals/{id}",
      parametersSchema: {
        type: "object",
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          description: { type: "string" },
          stage: { type: "string", enum: STAGE_ENUM },
          amount: { type: "number" },
          currency: { type: "string" },
          probability: { type: "number" },
          expectedCloseDate: { type: "string" },
          closedAt: { type: "string" },
          lostReason: { type: "string" },
          contactId: { type: "string" },
          companyId: { type: "string" },
          ownerId: { type: "string" },
          source: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Updated deal record",
    },
    {
      name: "delete_deal",
      description: "Delete a deal. Linked contact/company are not affected.",
      method: "DELETE",
      endpoint: "/api/deals/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "{ deleted: true }",
    },
  ],
};
