import type { BlockManifest } from "../manifest";

const FORMAT_ENUM = ["IN_PERSON", "ONLINE", "HYBRID", "SELF_PACED"];
const STATUS_ENUM = [
  "DRAFT",
  "SCHEDULED",
  "OPEN",
  "SOLD_OUT",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
];

export const experiencesBlock: BlockManifest = {
  kind: "block",
  name: "experiences",
  displayName: "Experiences",
  description:
    "Curated experiences offered by the organization — workshops, retreats, immersive events, classes. Each experience has a format (IN_PERSON/ONLINE/HYBRID/SELF_PACED), a lifecycle status (DRAFT/SCHEDULED/OPEN/SOLD_OUT/IN_PROGRESS/COMPLETED/CANCELLED), schedule (startDate/endDate/durationMin), logistics (locationName/locationUrl/capacity), pricing (price/currency), a cover image, an optional host, and rich content. Sits in the Commerce category alongside Products and Services.",
  types: ["experience"],
  capabilities: ["read", "create", "update", "delete"],
  models: ["Experience"],
  dependencies: [],
  paths: {
    components: "src/components/experiences/",
    pages: "src/app/admin/blocks/experiences/",
    api: "src/app/api/experiences/",
    validators: "src/lib/validators/experiences.ts",
    provider: "src/lib/chat/providers/experience.provider.ts",
  },
  actions: [
    {
      name: "list_experiences",
      description:
        "List experiences with optional filters by status, format, hostId, tag, and keyword search across name/headline/description/locationName/contentText",
      method: "GET",
      endpoint: "/api/experiences",
      parametersSchema: {
        type: "object",
        properties: {
          status: { type: "string", enum: STATUS_ENUM },
          format: { type: "string", enum: FORMAT_ENUM },
          hostId: { type: "string" },
          tag: { type: "string" },
          search: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
        },
      },
      responseDescription: "{ experiences: Experience[], total: number }",
    },
    {
      name: "get_experience",
      description: "Get a single experience by ID",
      method: "GET",
      endpoint: "/api/experiences/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Experience record",
    },
    {
      name: "create_experience",
      description: "Create a new experience",
      method: "POST",
      endpoint: "/api/experiences",
      parametersSchema: {
        type: "object",
        properties: {
          name: { type: "string" },
          headline: { type: "string" },
          description: { type: "string" },
          format: { type: "string", enum: FORMAT_ENUM },
          status: { type: "string", enum: STATUS_ENUM },
          startDate: { type: "string" },
          endDate: { type: "string" },
          durationMin: { type: "number" },
          locationName: { type: "string" },
          locationUrl: { type: "string" },
          capacity: { type: "number" },
          price: { type: "number" },
          currency: { type: "string" },
          coverImageUrl: { type: "string" },
          hostId: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["name"],
      },
      requiredFields: ["name"],
      responseDescription: "Created experience record",
    },
    {
      name: "update_experience",
      description: "Update an existing experience",
      method: "PATCH",
      endpoint: "/api/experiences/{id}",
      parametersSchema: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          headline: { type: "string" },
          description: { type: "string" },
          format: { type: "string", enum: FORMAT_ENUM },
          status: { type: "string", enum: STATUS_ENUM },
          startDate: { type: "string" },
          endDate: { type: "string" },
          durationMin: { type: "number" },
          locationName: { type: "string" },
          locationUrl: { type: "string" },
          capacity: { type: "number" },
          price: { type: "number" },
          currency: { type: "string" },
          coverImageUrl: { type: "string" },
          hostId: { type: "string" },
          contentJson: { type: "object" },
          contentText: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "Updated experience record",
    },
    {
      name: "delete_experience",
      description: "Delete an experience",
      method: "DELETE",
      endpoint: "/api/experiences/{id}",
      parametersSchema: {
        type: "object",
        properties: { id: { type: "string" } },
        required: ["id"],
      },
      requiredFields: ["id"],
      responseDescription: "{ deleted: true }",
    },
  ],
};
