/**
 * Generate the global glossary entry (herd.meta.glossary) by aggregating
 * the `## Glossary` sections of every other Handbook entry.
 *
 * Deterministic: same input ⇒ byte-identical output. The "Last updated"
 * line is derived from the `updated:` field of contributing entries
 * (max), never from `Date.now()`. If no terms are aggregated, the line
 * is omitted entirely.
 */

import "dotenv/config";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import fastGlob from "fast-glob";
import matter from "gray-matter";
import { parse as parseYaml } from "yaml";

const ROOT = resolve(__dirname, "..");
const HANDBOOK_ROOT = join(ROOT, "docs/handbook");
const GLOSSARY_DIR = join(HANDBOOK_ROOT, "_meta/glossary");
const GLOSSARY_UID = "herd.meta.glossary";

type Locale = "pt-BR" | "en-US";

interface FeatureYml {
  id: string;
  uid: string;
  level: string;
  parent: string | null;
  title: { "pt-BR": string; "en-US": string };
  updated: string;
}

interface EntryRef {
  uid: string;
  /** Path relative to docs/handbook, e.g. "networks/(overview)". */
  path: string;
  level: string;
  url: string;
  title: { "pt-BR": string; "en-US": string };
  updated: string;
}

interface ParsedTerm {
  term: string;
  definition: string;
}

interface AggregatedTerm {
  term: string;
  origins: Array<{ entry: EntryRef; definition: string }>;
}

const TERM_REGEX = /^-\s+\*\*(.+?)\*\*\s*:\s*(.+)$/gm;

const TRANSLATION_PENDING: Record<Locale, (other: Locale) => string> = {
  "pt-BR": (other) => `> Tradução pendente. Disponível em ${other}.`,
  "en-US": (other) => `> Translation pending. Available in ${other}.`,
};

const STRINGS = {
  "pt-BR": {
    heading: "# Glossário",
    intro:
      "Glossário global agregado a partir das seções `## Glossary` de todas as entries do Handbook. Gerado automaticamente por `npm run gen:glossary`.",
    lastUpdated: "Última atualização",
    empty:
      "*Nenhum termo definido ainda. Termos aparecem aqui conforme as entries do Handbook preenchem suas seções `## Glossary`.*",
    from: "From",
  },
  "en-US": {
    heading: "# Glossary",
    intro:
      "Global glossary aggregated from the `## Glossary` sections of all Handbook entries. Auto-generated by `npm run gen:glossary`.",
    lastUpdated: "Last updated",
    empty:
      "*No terms defined yet. Terms appear here as Handbook entries populate their `## Glossary` sections.*",
    from: "From",
  },
} as const;

async function main() {
  const entries = await collectEntries();

  for (const locale of ["pt-BR", "en-US"] as const) {
    const otherLocale: Locale = locale === "pt-BR" ? "en-US" : "pt-BR";
    const aggregated = aggregateGlossary(entries, locale, otherLocale);
    const lastUpdated = computeLastUpdated(aggregated);
    const body = renderGlossaryBody(aggregated, locale, lastUpdated);
    writeGlossaryFile(locale, body);
  }

  console.log(`✓ docs/handbook/_meta/glossary/{pt-BR,en-US}.md regenerated`);
}

async function collectEntries(): Promise<EntryRef[]> {
  const featureYmls = await fastGlob("**/feature.yml", {
    cwd: HANDBOOK_ROOT,
    absolute: false,
  });
  featureYmls.sort();

  const entries: EntryRef[] = [];
  for (const ymlPath of featureYmls) {
    const fullPath = join(HANDBOOK_ROOT, ymlPath);
    const yml = parseYaml(readFileSync(fullPath, "utf-8")) as FeatureYml;
    if (yml.uid === GLOSSARY_UID) continue;

    entries.push({
      uid: yml.uid,
      path: ymlPath.replace(/\/feature\.yml$/, ""),
      level: yml.level,
      url: buildUrl(yml),
      title: yml.title,
      updated: yml.updated ?? "",
    });
  }
  return entries;
}

function buildUrl(yml: FeatureYml): string {
  if (yml.level === "meta") return `/admin/handbook/meta/${yml.id}`;
  if (yml.level === "layer") return `/admin/handbook/${yml.id}`;
  if (yml.level === "category") {
    const layerId = yml.parent?.split(".").pop();
    return `/admin/handbook/${layerId}/${yml.id}`;
  }
  // feature: parent is herd.category.{layer}.{cat}
  const parts = yml.parent?.split(".") ?? [];
  const layerId = parts[2];
  const categoryId = parts[3];
  return `/admin/handbook/${layerId}/${categoryId}/${yml.id}`;
}

function aggregateGlossary(
  entries: EntryRef[],
  locale: Locale,
  otherLocale: Locale,
): AggregatedTerm[] {
  const map = new Map<string, AggregatedTerm>();

  for (const entry of entries) {
    let definitions = parseGlossaryFromMd(entry, locale);

    if (definitions.length === 0) {
      const otherDefs = parseGlossaryFromMd(entry, otherLocale);
      if (otherDefs.length > 0) {
        definitions = otherDefs.map((d) => ({
          term: d.term,
          definition: TRANSLATION_PENDING[locale](otherLocale),
        }));
      }
    }

    for (const { term, definition } of definitions) {
      const key = normalizeKey(term);
      if (!map.has(key)) map.set(key, { term, origins: [] });
      map.get(key)!.origins.push({ entry, definition });
    }
  }

  const sorted = [...map.values()].sort((a, b) =>
    normalizeKey(a.term).localeCompare(normalizeKey(b.term)),
  );

  for (const t of sorted) {
    t.origins.sort((a, b) => {
      const oa = levelOrder(a.entry.level);
      const ob = levelOrder(b.entry.level);
      if (oa !== ob) return oa - ob;
      return a.entry.path.localeCompare(b.entry.path);
    });
  }

  return sorted;
}

function levelOrder(level: string): number {
  if (level === "layer") return 0;
  if (level === "category") return 1;
  if (level === "meta") return 3;
  return 2; // network/solution/tool/block/integration
}

function parseGlossaryFromMd(entry: EntryRef, locale: Locale): ParsedTerm[] {
  const path = join(HANDBOOK_ROOT, entry.path, `${locale}.md`);
  let raw: string;
  try {
    raw = readFileSync(path, "utf-8");
  } catch {
    return [];
  }
  const body = matter(raw).content;
  const section = extractGlossarySection(body);
  if (!section) return [];

  const terms: ParsedTerm[] = [];
  let m: RegExpExecArray | null;
  TERM_REGEX.lastIndex = 0;
  while ((m = TERM_REGEX.exec(section)) !== null) {
    terms.push({ term: m[1].trim(), definition: m[2].trim() });
  }

  // Dedup within the same entry (first wins)
  const seen = new Set<string>();
  return terms.filter((t) => {
    const k = normalizeKey(t.term);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

function extractGlossarySection(body: string): string | null {
  const lines = body.split("\n");
  let inSection = false;
  let inFence = false;
  const collected: string[] = [];

  for (const line of lines) {
    if (line.startsWith("```")) inFence = !inFence;

    if (!inFence && /^## Glossary\b/.test(line)) {
      inSection = true;
      continue;
    }
    if (inSection) {
      if (!inFence && /^## /.test(line)) break;
      collected.push(line);
    }
  }
  return collected.length > 0 ? collected.join("\n") : null;
}

function normalizeKey(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
}

function computeLastUpdated(terms: AggregatedTerm[]): string | null {
  if (terms.length === 0) return null;
  const dates: string[] = [];
  for (const t of terms) {
    for (const o of t.origins) {
      if (o.entry.updated) dates.push(o.entry.updated);
    }
  }
  if (dates.length === 0) return null;
  // Lexicographic sort works for YYYY-MM-DD
  return dates.sort().reverse()[0];
}

function renderGlossaryBody(
  terms: AggregatedTerm[],
  locale: Locale,
  lastUpdated: string | null,
): string {
  const t = STRINGS[locale];
  const out: string[] = [];

  out.push(t.heading);
  out.push("");
  out.push(t.intro);
  out.push("");

  if (lastUpdated) {
    out.push(`**${t.lastUpdated}:** ${lastUpdated}`);
    out.push("");
  }

  out.push("<!-- BEGIN_GENERATED_GLOSSARY -->");
  out.push("");

  if (terms.length === 0) {
    out.push(t.empty);
    out.push("");
  } else {
    for (const aggregated of terms) {
      out.push(`### ${aggregated.term}`);
      out.push("");
      for (const origin of aggregated.origins) {
        const titleInLocale =
          origin.entry.title[locale] ?? origin.entry.title["en-US"];
        out.push(`**${t.from} [${titleInLocale}](${origin.entry.url}):**`);
        out.push("");
        out.push(origin.definition);
        out.push("");
      }
    }
  }

  out.push("<!-- END_GENERATED_GLOSSARY -->");
  out.push("");

  return out.join("\n");
}

function writeGlossaryFile(locale: Locale, body: string) {
  const path = join(GLOSSARY_DIR, `${locale}.md`);
  const existing = readFileSync(path, "utf-8");
  const parsed = matter(existing);
  const output = matter.stringify(body, parsed.data);
  writeFileSync(path, output, "utf-8");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
