/**
 * TypeScript types reflecting Braintree SDK `WebhookNotification` payload
 * shapes (`braintree` v3.x — Transaction / Subscription / Customer subjects).
 *
 * Production payloads are fuller than the sample notifications generated by
 * `gateway.webhookTesting.sampleNotification()`. Mappers must tolerate
 * optional fields — samples omit `customer`, `customerId`, `paymentMethodToken`,
 * `processedAt`, plan + price fields, etc. (see Sub-etapa 14 discovery).
 */

export interface BraintreeTransactionPayload {
  id: string;
  status: string;
  type?: "sale" | "credit";
  amount: string; // decimal string e.g. "29.99"
  currencyIsoCode?: string;
  merchantAccountId?: string;
  paymentInstrumentType?: string;
  // Customer reference (production) — pode faltar em sample notifications.
  customer?: {
    id?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
  };
  customerId?: string;
  // Subscription reference.
  subscriptionId?: string;
  // Payment method token.
  paymentMethodToken?: string;
  // Card details (when paymentInstrumentType === "credit_card").
  creditCard?: {
    last4?: string;
    cardType?: string;
  };
  // Timestamps.
  createdAt?: string;
  updatedAt?: string;
  // Failure details.
  processorResponseCode?: string;
  processorResponseText?: string;
  // Refund tracking (skip V1).
  refundedTransactionId?: string;
  refundIds?: string[];
}

export interface BraintreeSubscriptionPayload {
  id: string;
  status?: string; // "Active" | "Canceled" | "Expired" | "Past Due" | "Pending"
  planId?: string;
  customerId?: string;
  paymentMethodToken?: string;
  price?: string;
  nextBillingDate?: string;
  billingPeriodEndDate?: string;
  createdAt?: string;
  updatedAt?: string;
  transactions?: BraintreeTransactionPayload[];
  addOns?: unknown[];
  discounts?: unknown[];
}

export interface BraintreeCustomerPayload {
  id: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  company?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface BraintreeMapperContext {
  tenantId: string;
  providerId: string;
}
