import bcrypt from "bcryptjs";
import type { MemberRole, OrganizationInvitation } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getEmailProvider } from "@/lib/email";
import { buildInvitationEmail } from "@/lib/email/templates/invitation";
import { writeAuditLog } from "@/lib/audit/write-audit-log";
import {
  InvitationAlreadyExistsError,
  InvitationNotFoundError,
  InvitationAlreadyProcessedError,
  InvitationExpiredError,
  InvitationNotRevocableError,
  InvitationPasswordRequiredError,
  InvitationPasswordTooShortError,
} from "./errors";

const INVITATION_EXPIRES_DAYS = 7;

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CreateInvitationInput {
  organizationId: string;
  email: string;
  role: MemberRole;
  createdById: string;
}

export interface AcceptInvitationInput {
  token: string;
  password?: string;
}

export interface RevokeInvitationInput {
  token: string;
  organizationId: string;
}

export interface InvitationWithOrg {
  invitation: OrganizationInvitation;
  organization: {
    id: string;
    name: string;
    subdomain: string;
  };
}

// ─── 3.1 createInvitation ────────────────────────────────────────────────────

export async function createInvitation(
  input: CreateInvitationInput
): Promise<OrganizationInvitation> {
  const email = input.email.toLowerCase().trim();
  const { organizationId, role, createdById } = input;

  const now = new Date();

  // Dedup: reject if PENDING non-expired invitation already exists (Decision #3)
  const existing = await prisma.organizationInvitation.findFirst({
    where: {
      email,
      organizationId,
      status: "PENDING",
      expiresAt: { gt: now },
    },
  });
  if (existing) throw new InvitationAlreadyExistsError();

  // Create with 7-day expiry; token generated by DB default (gen_random_uuid)
  const expiresAt = new Date(now.getTime() + INVITATION_EXPIRES_DAYS * 24 * 60 * 60 * 1000);

  const invitation = await prisma.organizationInvitation.create({
    data: {
      organizationId,
      email,
      role,
      createdById,
      expiresAt,
      status: "PENDING",
    },
  });

  // Audit: invitation created. Recorded right after the row commits, before
  // the (fallible) email send, so the trail reflects the invite's existence
  // regardless of email delivery. Best-effort — never blocks the invite.
  await writeAuditLog({
    tenantId: organizationId,
    actorProfileId: createdById,
    action: "invitation.created",
    resourceType: "invitation",
    resourceId: invitation.id,
    metadata: { email, role },
  });

  // Fetch org name + inviter name for email template
  const [org, inviter] = await Promise.all([
    prisma.organization.findUnique({
      where: { id: organizationId },
      select: { name: true },
    }),
    prisma.networkProfile.findUnique({
      where: { id: createdById },
      select: { firstName: true, lastName: true },
    }),
  ]);

  const baseUrl = process.env.NEXTAUTH_URL ?? "http://lvh.me:3000";
  const acceptUrl = `${baseUrl}/accept/${invitation.token}`;
  const inviterName = inviter
    ? `${inviter.firstName} ${inviter.lastName}`.trim()
    : "Alguém";

  await getEmailProvider().send(
    buildInvitationEmail({
      recipientEmail: email,
      organizationName: org?.name ?? organizationId,
      inviterName,
      acceptUrl,
      expiresAt,
    })
  );

  return invitation;
}

// ─── 3.2 getInvitationByToken ────────────────────────────────────────────────

export async function getInvitationByToken(
  token: string
): Promise<InvitationWithOrg | null> {
  const invitation = await prisma.organizationInvitation.findUnique({
    where: { token },
    include: {
      organization: {
        select: { id: true, name: true, subdomain: true },
      },
    },
  });

  if (!invitation) return null;

  return {
    invitation,
    organization: invitation.organization,
  };
}

// ─── 3.3 acceptInvitation ────────────────────────────────────────────────────

export async function acceptInvitation(input: AcceptInvitationInput): Promise<{
  profile: { id: string; email: string };
  membership: { id: string; organizationId: string };
}> {
  const { token, password } = input;

  // Load invitation
  const invitation = await prisma.organizationInvitation.findUnique({
    where: { token },
    include: { organization: { select: { id: true, localeDefault: true } } },
  });
  if (!invitation) throw new InvitationNotFoundError();

  // Status check (non-PENDING was already processed)
  if (invitation.status !== "PENDING") throw new InvitationAlreadyProcessedError();

  // Expiry check — mutate to EXPIRED on first attempted accept
  const now = new Date();
  if (invitation.expiresAt && now > invitation.expiresAt) {
    await prisma.organizationInvitation.update({
      where: { id: invitation.id },
      data: { status: "EXPIRED" },
    });
    throw new InvitationExpiredError();
  }

  // Resolve or create NetworkProfile
  let profile = await prisma.networkProfile.findUnique({
    where: { email: invitation.email },
    select: { id: true, email: true },
  });

  if (!profile) {
    // New user path: password required, min 8 chars (Decision #4)
    if (!password) throw new InvitationPasswordRequiredError();
    if (password.length < 8) throw new InvitationPasswordTooShortError();

    const passwordHash = await bcrypt.hash(password, 10);
    profile = await prisma.networkProfile.create({
      data: {
        email: invitation.email,
        firstName: invitation.email.split("@")[0],
        lastName: "",
        passwordHash,
        status: "ACTIVE",
        // Inherit the inviting organization's default locale instead of the
        // schema default, so the new member's UI matches the org they joined.
        locale: invitation.organization.localeDefault ?? undefined,
      },
      select: { id: true, email: true },
    });
  }

  // Idempotency: if already an ACTIVE member, just mark invitation ACCEPTED
  const existingMembership = await prisma.organizationMember.findUnique({
    where: {
      organizationId_networkProfileId: {
        organizationId: invitation.organizationId,
        networkProfileId: profile.id,
      },
    },
  });

  if (existingMembership && existingMembership.status === "ACTIVE") {
    await prisma.organizationInvitation.update({
      where: { id: invitation.id },
      data: { status: "ACCEPTED", acceptedAt: now },
    });
    // Audit: invitation accepted (idempotent path — already an ACTIVE member).
    // Actor is the accepting profile itself. Runs after the update commits.
    await writeAuditLog({
      tenantId: invitation.organizationId,
      actorProfileId: profile.id,
      action: "invitation.accepted",
      resourceType: "invitation",
      resourceId: invitation.id,
      metadata: { email: invitation.email, role: invitation.role, idempotent: true },
    });
    return { profile, membership: existingMembership };
  }

  // Transactional: create membership + role + mark invitation ACCEPTED
  const [membership] = await prisma.$transaction([
    prisma.organizationMember.create({
      data: {
        organizationId: invitation.organizationId,
        networkProfileId: profile.id,
        status: "ACTIVE",
        roles: {
          create: {
            role: invitation.role,
            scopeType: "ORG",
          },
        },
      },
    }),
    prisma.organizationInvitation.update({
      where: { id: invitation.id },
      data: { status: "ACCEPTED", acceptedAt: now },
    }),
  ]);

  // Audit: invitation accepted (main path — membership + role just created).
  // Runs AFTER the $transaction commits so an audit failure can never roll
  // back the membership. Actor is the accepting profile itself.
  await writeAuditLog({
    tenantId: invitation.organizationId,
    actorProfileId: profile.id,
    action: "invitation.accepted",
    resourceType: "invitation",
    resourceId: invitation.id,
    metadata: { email: invitation.email, role: invitation.role },
  });

  return { profile, membership };
}

// ─── 3.4 revokeInvitation ────────────────────────────────────────────────────

export async function revokeInvitation(input: RevokeInvitationInput): Promise<void> {
  const { token, organizationId } = input;

  const invitation = await prisma.organizationInvitation.findFirst({
    where: { token, organizationId },
  });
  if (!invitation) throw new InvitationNotFoundError();
  if (invitation.status !== "PENDING") throw new InvitationNotRevocableError();

  // Revoke via expiresAt = now() (Decision #6 — no REVOKED enum value)
  await prisma.organizationInvitation.update({
    where: { id: invitation.id },
    data: { expiresAt: new Date() },
  });
}

// ─── 3.5 listPendingInvitations ──────────────────────────────────────────────

export async function listPendingInvitations(
  organizationId: string
): Promise<OrganizationInvitation[]> {
  const now = new Date();
  return prisma.organizationInvitation.findMany({
    where: {
      organizationId,
      status: "PENDING",
      expiresAt: { gt: now },
    },
    orderBy: { createdAt: "desc" },
  });
}
